sonar.projectKey=disnana_NanaSQLite
sonar.organization=disnana
sonar.sources=src
sonar.tests=tests
sonar.exclusions=scripts/**,docs/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
